/* APKHub — read-path application.
 *
 * Architecture: a tiny unidirectional store + derived views.
 *   store.setState(partial) -> notify subscribers -> render current view
 *
 * Data: fetched from data/apps.json (static, generated by the indexer).
 *       Falls back to an embedded SEED so the UI is explorable offline / in a
 *       restricted preview sandbox with no network access.
 *
 * Search: a hand-rolled inverted index over tokenised text. O(queries) with
 *         AND semantics + prefix matching. Swap for FlexSearch/MiniSearch at
 *         ~100k records without changing the API.
 */

(() => {
  "use strict";

  // ------------------------------------------------------------------ store
  const store = (() => {
    const state = {
      apps: [],
      meta: {},
      query: "",
      category: "All",
      sort: "trending",
      license: "",
      lang: "",
      minSdk: "",
      view: "home", // home | grid | favourites | detail
      detailSlug: null,
      onlyFav: false,
      loading: true,
    };
    const subs = new Set();
    return {
      get: () => state,
      set: (patch) => {
        Object.assign(state, patch);
        subs.forEach((fn) => fn(state));
      },
      sub: (fn) => (subs.add(fn), () => subs.delete(fn)),
    };
  })();

  // --------------------------------------------------------------- persistence
  const FAV_KEY = "apkhub.favs.v1";
  const THEME_KEY = "apkhub.theme";
  const favs = new Set(JSON.parse(localStorage.getItem(FAV_KEY) || "[]"));
  const saveFavs = () => localStorage.setItem(FAV_KEY, JSON.stringify([...favs]));

  // --------------------------------------------------------------- formatting
  const fmtSize = (b) => {
    if (b == null) return "—";
    if (b < 1024) return b + " B";
    const u = ["KB", "MB", "GB"];
    let i = -1, n = b;
    do { n /= 1024; i++; } while (n >= 1024 && i < 2);
    return n.toFixed(n < 10 ? 1 : 0) + " " + u[i];
  };
  const fmtNum = (n) => n >= 1000 ? (n / 1000).toFixed(n >= 10000 ? 0 : 1) + "k" : "" + n;
  const fmtDate = (iso) => {
    if (!iso) return "—";
    const d = new Date(iso);
    return isNaN(d) ? "—" : d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  };
  const esc = (s) => (s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const initials = (name) => (name || "?").replace(/[^A-Za-z0-9]/g, " ").trim().split(/\s+/).slice(0, 2).map((w) => w[0] || "").join("").toUpperCase() || "?";

  // --------------------------------------------------------------- search index
  const tokenize = (s) =>
    (s || "")
      .toLowerCase()
      .normalize("NFD").replace(/[\u0300-\u036f]/g, "") // accent-fold
      .split(/[^a-z0-9]+/)
      .filter(Boolean);

  const SearchIndex = {
    map: new Map(), // token -> Set(appIndex)
    docs: [], // token arrays per app
    build(apps) {
      this.map.clear(); this.docs = [];
      apps.forEach((app, i) => {
        const text = [app.name, app.owner, app.description, ...(app.topics || []), app.language].join(" ");
        const toks = tokenize(text);
        this.docs[i] = toks;
        const seen = new Set(toks);
        seen.forEach((t) => {
          if (!this.map.has(t)) this.map.set(t, new Set());
          this.map.get(t).add(i);
        });
      });
    },
    search(q, apps) {
      const terms = tokenize(q);
      if (!terms.length) return apps.map((_, i) => i);
      // AND of postings, with prefix expansion on the last term.
      let result = null;
      terms.forEach((term, ti) => {
        const isLast = ti === terms.length - 1;
        let postings = this.map.get(term);
        if (!postings && isLast) {
          // prefix match
          postings = new Set();
          for (const [tok, idx] of this.map) if (tok.startsWith(term)) for (const x of idx) postings.add(x);
        }
        if (!postings) postings = new Set(); // term absent -> empty intersection
        result = result === null ? new Set(postings) : new Set([...result].filter((x) => postings.has(x)));
      });
      // rank: name-startswith > name-contains > others; then stars.
      const ranked = [...result].sort((a, b) => {
        const A = apps[a], B = apps[b];
        const score = (app) => {
          const n = (app.name || "").toLowerCase();
          let s = 0;
          terms.forEach((t) => { if (n.startsWith(t)) s += 3; else if (n.includes(t)) s += 1; });
          return s + Math.log10((app.stars || 0) + 1) * 0.5;
        };
        return score(B) - score(A);
      });
      return ranked;
    },
  };

  // --------------------------------------------------------------- icons
  const STAR_SVG = '<svg width="13" height="13" viewBox="0 0 24 24"><path fill="currentColor" d="m12 17.3-6.2 3.7 1.6-7L2 9.2l7.2-.6L12 2l2.8 6.6 7.2.6-5.4 4.8 1.6 7Z"/></svg>';
  const DL_SVG = '<svg width="15" height="15" viewBox="0 0 24 24"><path fill="currentColor" d="M12 3a1 1 0 0 1 1 1v9.6l3.3-3.3 1.4 1.4L12 17.4l-5.7-5.7 1.4-1.4L11 13.6V4a1 1 0 0 1 1-1ZM5 19h14v2H5Z"/></svg>';
  const HEART_SVG = '<svg width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="m12 21.35-1.45-1.32C5.4 15.36 2 12.27 2 8.5 2 5.41 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.08C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.41 22 8.5c0 3.77-3.4 6.86-8.55 11.53L12 21.35Z"/></svg>';
  const CLOCK_SVG = '<svg width="13" height="13" viewBox="0 0 24 24"><path fill="currentColor" d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm1 11h-5v-2h3V6h2Z"/></svg>';
  const APK_SVG = '<svg width="13" height="13" viewBox="0 0 24 24"><path fill="currentColor" d="M7 2a1 1 0 0 0-1 1v3h2V4h8v16H8v-2H6v3a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H7Z"/></svg>';

  // --------------------------------------------------------------- icon render
  function appIcon(app, cls = "") {
    const c = app.color || "#333";
    return `<div class="app-icon placeholder ${cls}" style="background:${c}" aria-hidden="true">${esc(initials(app.name))}</div>`;
  }

  // --------------------------------------------------------------- card
  function card(app) {
    const on = favs.has(app.slug);
    const lic = app.license
      ? `<span class="meta license" title="License">${esc(app.license)}</span>`
      : `<span class="meta warn" title="License not declared">No license</span>`;
    const lang = app.language ? `<span class="meta">${esc(app.language)}</span>` : "";
    const arch = app.recommendedAsset?.arch ? `<span class="meta">${esc(app.recommendedAsset.arch)}</span>` : "";
    return `
    <article class="card" data-slug="${esc(app.slug)}">
      <div class="card-top">
        ${appIcon(app)}
        <div class="card-titles">
          <div class="card-name">${esc(app.name)}</div>
          <div class="card-owner">by <a href="${esc(app.repoUrl)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${esc(app.owner)}</a></div>
        </div>
        <button class="fav-toggle ${on ? "on" : ""}" data-fav="${esc(app.slug)}" title="${on ? "Remove from" : "Add to"} favourites" aria-label="Toggle favourite" aria-pressed="${on}">${HEART_SVG}</button>
      </div>
      <p class="card-desc">${esc(app.description || "No description available.")}</p>
      <div class="card-meta">
        <span class="meta">v${esc(app.version || "?")}</span>
        ${lic}${lang}${arch}
      </div>
      <div class="card-foot">
        <div class="card-stats">
          <span class="stat">${STAR_SVG}${fmtNum(app.stars)}</span>
          <span class="stat">${fmtSize(app.size)}</span>
          <span class="stat" title="${fmtDate(app.publishedAt)}">${CLOCK_SVG}${fmtDate(app.publishedAt)}</span>
        </div>
        <a class="btn" href="${esc(app.downloadUrl)}" target="_blank" rel="noopener nofollow" onclick="event.stopPropagation()" title="Download APK from GitHub">${DL_SVG}Get</a>
      </div>
    </article>`;
  }

  // --------------------------------------------------------------- filter pipe
  function derive() {
    const { apps, query, category, sort, license, lang, minSdk, onlyFav } = store.get();
    let idx = SearchIndex.search(query, apps);
    let list = idx.map((i) => apps[i]);

    if (category !== "All") list = list.filter((a) => a.category === category);
    if (license) list = list.filter((a) => (license === "NONE" ? !a.license : a.license === license));
    if (lang) list = list.filter((a) => a.language === lang);
    if (minSdk) list = list.filter((a) => a.minSdk == null || a.minSdk >= +minSdk);
    if (onlyFav) list = list.filter((a) => favs.has(a.slug));

    const sorters = {
      trending: (a, b) => b.score - a.score,
      stars: (a, b) => b.stars - a.stars,
      newest: (a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0),
      name: (a, b) => (a.name || "").localeCompare(b.name || ""),
      size: (a, b) => (a.size || 1e12) - (b.size || 1e12),
    };
    list.sort(sorters[sort] || sorters.trending);
    return list;
  }

  // --------------------------------------------------------------- views
  function renderHome() {
    const { apps } = store.get();
    const trending = [...apps].sort((a, b) => b.score - a.score).slice(0, 12);
    const recent = [...apps]
      .sort((a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0))
      .slice(0, 12);
    return `
      <div class="hero">
        <h2>Find open-source Android apps, straight from GitHub.</h2>
        <p>APKHub indexes public GitHub releases and surfaces every APK in one
        fast, searchable, ad-free catalogue. Every download links to the
        official asset — we never re-host anything.</p>
      </div>
      <div class="section-title">🔥 Trending</div>
      <div class="trending">${trending.map(card).join("")}</div>
      <div class="section-title">🆕 Recently updated</div>
      <div class="grid">${recent.map(card).join("")}</div>`;
  }

  function renderGrid() {
    const list = derive();
    const { view, onlyFav } = store.get();
    const heading = onlyFav ? "Your favourites" : view === "grid" && store.get().category !== "All" ? store.get().category : "All apps";
    const clearBtn = (store.get().query || onlyFav) ? `<button class="btn ghost clear" id="clearAll">Clear</button>` : "";
    if (!list.length) {
      return `<div class="view-head"><h1>${esc(heading)}</h1><span class="count">0 apps</span>${clearBtn}</div>
        <div class="empty"><div class="big">🔍</div>No apps match your filters. Try widening your search.</div>`;
    }
    return `<div class="view-head"><h1>${esc(heading)}</h1><span class="count">${list.length} app${list.length === 1 ? "" : "s"}</span>${clearBtn}</div>
      <div class="grid">${list.map(card).join("")}</div>`;
  }

  function renderLoading() {
    const skel = `<div class="skeleton-card"></div>`;
    return `<div class="grid">${skel.repeat(9)}</div>`;
  }

  function renderView() {
    const { view, loading } = store.get();
    const root = document.getElementById("view");
    if (loading) { root.innerHTML = renderLoading(); return; }
    root.innerHTML = view === "home" ? renderHome() : renderGrid();
    root.querySelectorAll(".card").forEach((el) => el.addEventListener("click", () => openDetail(el.dataset.slug)));
    root.querySelectorAll("[data-fav]").forEach((el) => el.addEventListener("click", (e) => { e.stopPropagation(); toggleFav(el.dataset.fav); }));
    const clear = document.getElementById("clearAll");
    if (clear) clear.addEventListener("click", () => store.set({ query: "", category: "All", onlyFav: false, license: "", lang: "", minSdk: "" }) || setSearch(""));
    document.getElementById("main").scrollIntoView({ block: "start" });
  }

  // --------------------------------------------------------------- detail modal
  function openDetail(slug) {
    const app = store.get().apps.find((a) => a.slug === slug);
    if (!app) return;
    location.hash = `#/app/${slug}`;
    showDetail(app);
  }
  function showDetail(app) {
    const panel = document.getElementById("modalPanel");
    const on = favs.has(app.slug);
    const lic = app.license
      ? `<span class="meta license">${esc(app.license)}</span>`
      : `<span class="meta warn">License not declared — verify before use</span>`;
    const shots = (app.screenshots || []).map((s) => `<img loading="lazy" src="${esc(s)}" alt="screenshot">`).join("");
    const tags = (app.topics || []).map((t) => `<span class="meta">${esc(t)}</span>`).join("");
    panel.innerHTML = `
      <button class="modal-close" data-close aria-label="Close">×</button>
      <div class="detail-head">
        ${appIcon(app)}
        <div>
          <h2 class="detail-name">${esc(app.name)}</h2>
          <div class="detail-owner">by <a href="${esc(app.repoUrl)}" target="_blank" rel="noopener">${esc(app.owner)}</a>${app.ownerType === "Organization" ? " (Organization)" : ""}</div>
          <div class="card-meta" style="margin-top:8px"><span class="meta">v${esc(app.version || "?")}</span>${lic}${app.language ? `<span class="meta">${esc(app.language)}</span>` : ""}</div>
        </div>
      </div>
      <p style="color:var(--text-dim);margin:0 0 8px">${esc(app.description || "No description provided.")}</p>
      <div class="detail-grid">
        <span class="k">Category</span><span class="v">${esc(app.category)}</span>
        <span class="k">Version</span><span class="v">${esc(app.version || "—")}</span>
        <span class="k">Updated</span><span class="v">${fmtDate(app.publishedAt)}</span>
        <span class="k">File size</span><span class="v">${fmtSize(app.size)}</span>
        <span class="k">Architecture</span><span class="v">${esc(app.recommendedAsset?.arch || "universal")}</span>
        <span class="k">Min Android</span><span class="v">${app.minSdk ? "API " + app.minSdk + " (Android " + sdkToVer(app.minSdk) + "+)" : "—"}</span>
        <span class="k">Stars</span><span class="v">${fmtNum(app.stars)} ⭐</span>
        <span class="k">License</span><span class="v">${app.license ? esc(app.license) : "Not declared"}</span>
      </div>
      ${shots ? `<div class="detail-section"><h3>Screenshots</h3><div class="detail-shots">${shots}</div></div>` : ""}
      ${app.releaseNotes ? `<div class="detail-section"><h3>Release notes</h3><div class="detail-notes">${app.releaseNotes}</div></div>` : ""}
      ${tags ? `<div class="detail-section"><h3>Topics</h3><div class="tag-row">${tags}</div></div>` : ""}
      <div class="detail-actions">
        <a class="btn full" href="${esc(app.downloadUrl)}" target="_blank" rel="noopener nofollow">${DL_SVG} Download APK (official)</a>
        <a class="btn ghost" href="${esc(app.releasePage)}" target="_blank" rel="noopener">Release page</a>
        <button class="btn ghost fav-toggle ${on ? "on" : ""}" data-fav="${esc(app.slug)}">${HEART_SVG}</button>
      </div>`;
    const m = document.getElementById("modal");
    m.hidden = false; m.setAttribute("aria-hidden", "false");
    document.body.style.overflow = "hidden";
    panel.querySelector("[data-fav]").addEventListener("click", () => toggleFav(app.slug, true));
  }
  function closeDetail() {
    const m = document.getElementById("modal");
    m.hidden = true; m.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
    if (location.hash.startsWith("#/app/")) history.replaceState(null, "", location.pathname + location.search);
  }
  function sdkToVer(sdk) {
    return { 21: "5.0", 23: "6.0", 24: "7.0", 26: "8.0", 28: "9", 29: "10", 30: "11", 31: "12", 33: "13", 34: "14" }[sdk] || "?";
  }

  // --------------------------------------------------------------- favourites
  function toggleFav(slug, inModal) {
    if (favs.has(slug)) favs.delete(slug); else favs.add(slug);
    saveFavs();
    updateFavBadge();
    // refresh visible favourite toggles
    document.querySelectorAll(`[data-fav="${slug}"]`).forEach((el) => {
      const on = favs.has(slug);
      el.classList.toggle("on", on);
      el.setAttribute("aria-pressed", on);
    });
    if (store.get().onlyFav) renderView();
    if (inModal && store.get().detailSlug === slug) {} // modal state handled by class toggle
  }
  function updateFavBadge() {
    const b = document.getElementById("favCount");
    if (favs.size) { b.hidden = false; b.textContent = favs.size; } else b.hidden = true;
  }

  // --------------------------------------------------------------- category chips + filter options
  function buildFacets() {
    const { apps } = store.get();
    const cats = ["All", ...new Set(apps.map((a) => a.category).filter(Boolean))].sort();
    document.getElementById("categoryChips").innerHTML = cats
      .map((c) => `<button class="chip ${c === store.get().category ? "active" : ""}" data-cat="${esc(c)}">${esc(c)}</button>`)
      .join("");
    document.querySelectorAll("[data-cat]").forEach((el) =>
      el.addEventListener("click", () => {
        store.set({ category: el.dataset.cat, view: "grid", onlyFav: false });
        syncChips();
        renderView();
      })
    );

    const licenses = [...new Set(apps.map((a) => a.license).filter(Boolean))].sort();
    const lf = document.getElementById("licenseFilter");
    lf.innerHTML = `<option value="">Any license</option>` + licenses.map((l) => `<option value="${esc(l)}">${esc(l)}</option>`).join("") + `<option value="NONE">No license</option>`;
    const langs = [...new Set(apps.map((a) => a.language).filter(Boolean))].sort();
    document.getElementById("langFilter").innerHTML = `<option value="">Any language</option>` + langs.map((l) => `<option value="${esc(l)}">${esc(l)}</option>`).join("");
  }
  function syncChips() {
    document.querySelectorAll("[data-cat]").forEach((el) => el.classList.toggle("active", el.dataset.cat === store.get().category));
  }

  // --------------------------------------------------------------- search input binding
  function setSearch(v) {
    document.getElementById("search").value = v;
  }

  // --------------------------------------------------------------- routing
  function route() {
    const h = location.hash;
    if (h.startsWith("#/app/")) {
      const slug = decodeURIComponent(h.slice("#/app/".length));
      store.set({ detailSlug: slug });
      const app = store.get().apps.find((a) => a.slug === slug);
      if (app) showDetail(app);
      else closeDetail();
    } else {
      closeDetail();
    }
  }

  // --------------------------------------------------------------- data loading
  async function load() {
    let data = null;
    try {
      const res = await fetch("data/apps.json", { cache: "no-cache" });
      if (res.ok) data = await res.json();
    } catch (e) { /* offline / sandboxed preview — fall through to seed */ }

    if (!data || !Array.isArray(data.apps) || !data.apps.length) {
      data = SEED_DATA;
    }
    SearchIndex.build(data.apps);
    store.set({ apps: data.apps, meta: data, loading: false });

    // index health footer
    if (data.generatedAt) {
      document.getElementById("healthApps").textContent = `${data.apps.length} apps indexed`;
      document.getElementById("healthDate").textContent = fmtDate(data.generatedAt);
      document.getElementById("indexHealth").hidden = false;
    }
    buildFacets();
    renderView();
    route();
  }

  // --------------------------------------------------------------- theme
  function applyTheme(t) {
    document.documentElement.setAttribute("data-theme", t);
    document.querySelector('meta[name="theme-color"]').setAttribute("content", t === "dark" ? "#0d1117" : "#f6f8fa");
    localStorage.setItem(THEME_KEY, t);
  }
  function initTheme() {
    const saved = localStorage.getItem(THEME_KEY);
    const pref = saved || (matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark");
    applyTheme(pref);
  }

  // --------------------------------------------------------------- wiring
  function init() {
    initTheme();
    updateFavBadge();

    let debounce;
    document.getElementById("search").addEventListener("input", (e) => {
      clearTimeout(debounce);
      debounce = setTimeout(() => {
        const v = e.target.value.trim();
        store.set({ query: v, view: v ? "grid" : store.get().view, onlyFav: false });
        if (v) renderView();
      }, 90);
    });

    document.getElementById("sort").addEventListener("change", (e) => { store.set({ sort: e.target.value }); renderView(); });
    document.getElementById("licenseFilter").addEventListener("change", (e) => { store.set({ license: e.target.value }); renderView(); });
    document.getElementById("langFilter").addEventListener("change", (e) => { store.set({ lang: e.target.value }); renderView(); });
    document.getElementById("minSdkFilter").addEventListener("change", (e) => { store.set({ minSdk: e.target.value }); renderView(); });

    document.getElementById("themeBtn").addEventListener("click", () => {
      applyTheme(document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark");
    });
    document.getElementById("favBtn").addEventListener("click", () => {
      store.set({ view: "grid", onlyFav: true, category: "All" });
      setSearch("");
      syncChips();
      renderView();
    });

    document.getElementById("brand")?.addEventListener("click", (e) => {
      // handled by anchor href; reset filters when going home
    });
    document.querySelector(".brand").addEventListener("click", () => {
      store.set({ view: "home", query: "", category: "All", onlyFav: false, license: "", lang: "", minSdk: "" });
      setSearch(""); syncChips(); renderView();
    });

    // modal close
    document.getElementById("modal").addEventListener("click", (e) => {
      if (e.target.dataset.close !== undefined || e.target.classList.contains("modal-backdrop")) closeDetail();
    });
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closeDetail();
      if (e.key === "/" && document.activeElement.id !== "search") {
        e.preventDefault(); document.getElementById("search").focus();
      }
    });
    window.addEventListener("hashchange", route);

    // PWA service worker (production only; skip in sandboxed preview).
    if ("serviceWorker" in navigator && location.protocol.startsWith("http")) {
      navigator.serviceWorker.register("sw.js").catch(() => {});
    }

    store.sub(renderView);
    load();
  }

  document.addEventListener("DOMContentLoaded", init);

  // --------------------------------------------------------------- embedded seed (offline fallback)
  // Mirrors the indexer's seed dataset so the UI is fully explorable without network.
  const SEED_DATA = {
    $schema: 1,
    generatedAt: "2026-06-14T09:00:00Z",
    apps: [
      { slug: "termux-termux-app", name: "Termux", owner: "termux", ownerType: "Organization", repo: "termux-app", repoUrl: "https://github.com/termux/termux-app", description: "Android terminal and Linux environment — apps installable with apt. No root required.", color: "#2d2d2d", category: "Tools", topics: ["android", "terminal", "linux", "bash"], language: "C++", license: "GPL-3.0", licenseDeclared: true, version: "0.118.1", minSdk: 24, publishedAt: "2025-11-02T00:00:00Z", size: 63180590, downloadUrl: "https://github.com/termux/termux-app/releases/download/v0.118.1/termux-app_v0.118.1+apt-android-7-github-debug_arm64-v8a.apk", releasePage: "https://github.com/termux/termux-app/releases/tag/v0.118.1", stars: 38200, score: 62.4, recommendedAsset: { arch: "arm64-v8a", abi: "arm64-v8a" }, screenshots: [] },
      { slug: "antennapod-antennapod", name: "AntennaPod", owner: "AntennaPod", ownerType: "Organization", repo: "AntennaPod", repoUrl: "https://github.com/AntennaPod/AntennaPod", description: "A podcast player that is simple and offers full control. Open source, no ads, respects your privacy.", color: "#1a73e8", category: "Media", topics: ["android", "podcast", "kotlin"], language: "Kotlin", license: "GPL-3.0", licenseDeclared: true, version: "3.5.1", minSdk: 21, publishedAt: "2026-02-18T00:00:00Z", size: 10240000, downloadUrl: "https://github.com/AntennaPod/AntennaPod/releases/download/3.5.1/AntennaPod-3.5.1-universal-release.apk", releasePage: "https://github.com/AntennaPod/AntennaPod/releases/tag/3.5.1", stars: 6900, score: 48.7, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "mihonapp-mihon", name: "Mihon", owner: "mihonapp", ownerType: "Organization", repo: "mihon", repoUrl: "https://github.com/mihonapp/mihon", description: "Free and open source manga reader for Android. The community successor to Tachiyomi.", color: "#7b1fa2", category: "Reading", topics: ["android", "manga", "reader", "kotlin"], language: "Kotlin", license: "Apache-2.0", licenseDeclared: true, version: "1.11.0", minSdk: 21, publishedAt: "2026-01-30T00:00:00Z", size: 22500000, downloadUrl: "https://github.com/mihonapp/mihon/releases/download/v1.11.0/mihon-1.11.0-universal.apk", releasePage: "https://github.com/mihonapp/mihon/releases/tag/v1.11.0", stars: 12500, score: 55.2, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "fossifyorg-gallery", name: "Fossify Gallery", owner: "FossifyOrg", ownerType: "Organization", repo: "Gallery", repoUrl: "https://github.com/FossifyOrg/Gallery", description: "Ad-free, privacy-friendly gallery app. Browse, edit and manage your photos offline.", color: "#00897b", category: "Media", topics: ["android", "gallery", "photos", "kotlin"], language: "Kotlin", license: "GPL-3.0", licenseDeclared: true, version: "1.2.0", minSdk: 23, publishedAt: "2026-03-10T00:00:00Z", size: 8400000, downloadUrl: "https://github.com/FossifyOrg/Gallery/releases/download/1.2.0/Gallery-1.2.0-foss.apk", releasePage: "https://github.com/FossifyOrg/Gallery/releases/tag/1.2.0", stars: 2100, score: 33.1, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "brave-browser", name: "Brave", owner: "brave", ownerType: "Organization", repo: "browser-android-tabs", repoUrl: "https://github.com/brave/browser-android-tabs", description: "Privacy-focused Android browser with a built-in ad blocker and HTTPS everywhere.", color: "#fb542b", category: "Internet", topics: ["android", "browser", "privacy", "kotlin"], language: "Kotlin", license: "MPL-2.0", licenseDeclared: true, version: "1.66.115", minSdk: 24, publishedAt: "2026-04-05T00:00:00Z", size: 215000000, downloadUrl: "https://github.com/brave/browser-android-tabs/releases/download/v1.66.115/Brave.apk", releasePage: "https://github.com/brave/browser-android-tabs/releases/tag/v1.66.115", stars: 610, score: 29.4, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "bitwarden-mobile", name: "Bitwarden", owner: "bitwarden", ownerType: "Organization", repo: "mobile", repoUrl: "https://github.com/bitwarden/mobile", description: "Open source password manager. Store and autofill logins securely across all your devices.", color: "#175ddc", category: "Security", topics: ["android", "password-manager", "security"], language: "C#", license: "GPL-3.0", licenseDeclared: true, version: "2026.4.0", minSdk: 25, publishedAt: "2026-04-22T00:00:00Z", size: 78000000, downloadUrl: "https://github.com/bitwarden/mobile/releases/download/v2026.4.0/com.x8bit.bitwarden.apk", releasePage: "https://github.com/bitwarden/mobile/releases/tag/v2026.4.0", stars: 2300, score: 31.0, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "osmandapp-osmand", name: "OsmAnd", owner: "osmandapp", ownerType: "Organization", repo: "OsmAnd", repoUrl: "https://github.com/osmandapp/OsmAnd", description: "Offline and online maps and navigation for Android, built on OpenStreetMap data.", color: "#388e3c", category: "Tools", topics: ["android", "maps", "navigation", "openstreetmap"], language: "Java", license: "GPL-3.0", licenseDeclared: true, version: "4.8.4", minSdk: 23, publishedAt: "2026-02-09T00:00:00Z", size: 145000000, downloadUrl: "https://github.com/osmandapp/OsmAnd/releases/download/4.8.4/OsmAnd-default.apk", releasePage: "https://github.com/osmandapp/OsmAnd/releases/tag/4.8.4", stars: 4900, score: 45.9, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "keepassdx-keepassdx", name: "KeePassDX", owner: "Kunzisoft", ownerType: "Organization", repo: "KeePassDX", repoUrl: "https://github.com/Kunzisoft/KeePassDX", description: "Lightweight password manager for Android, compatible with KeePass databases.", color: "#1565c0", category: "Security", topics: ["android", "password", "keepass", "security"], language: "Kotlin", license: "GPL-3.0", licenseDeclared: true, version: "4.0.3", minSdk: 21, publishedAt: "2026-03-25T00:00:00Z", size: 12000000, downloadUrl: "https://github.com/Kunzisoft/KeePassDX/releases/download/4.0.3/KeePassDX-4.0.3-universal.apk", releasePage: "https://github.com/Kunzisoft/KeePassDX/releases/tag/4.0.3", stars: 4500, score: 44.1, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "simplemobiletools-simple-calendar", name: "Simple Calendar", owner: "SimpleMobileTools", ownerType: "Organization", repo: "Simple-Calendar", repoUrl: "https://github.com/SimpleMobileTools/Simple-Calendar", description: "A simple calendar with events, reminders and widgets. No ads, no internet permission.", color: "#c62828", category: "Productivity", topics: ["android", "calendar", "kotlin"], language: "Kotlin", license: "GPL-3.0", licenseDeclared: true, version: "6.22.5", minSdk: 23, publishedAt: "2025-12-12T00:00:00Z", size: 6100000, downloadUrl: "https://github.com/SimpleMobileTools/Simple-Calendar/releases/download/6.22.5/calendar-release.apk", releasePage: "https://github.com/SimpleMobileTools/Simple-Calendar/releases/tag/6.22.5", stars: 3700, score: 36.8, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "newpipe-newpipe", name: "NewPipe", owner: "TeamNewPipe", ownerType: "Organization", repo: "NewPipe", repoUrl: "https://github.com/TeamNewPipe/NewPipe", description: "A lightweight YouTube frontend with background play and downloads. No Google services required.", color: "#cd201f", category: "Media", topics: ["android", "youtube", "media"], language: "Java", license: "GPL-3.0", licenseDeclared: true, version: "0.27.7", minSdk: 21, publishedAt: "2026-01-15T00:00:00Z", size: 9200000, downloadUrl: "https://github.com/TeamNewPipe/NewPipe/releases/download/v0.27.7/NewPipe_v0.27.7.apk", releasePage: "https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.7", stars: 32000, score: 58.9, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
      { slug: "vlc-vlc-android", name: "VLC for Android", owner: "videolan", ownerType: "Organization", repo: "vlc-android", repoUrl: "https://github.com/videolan/vlc-android", description: "Free and open source multimedia player that plays most audio and video files.", color: "#ff8800", category: "Media", topics: ["android", "video", "media-player"], language: "Java", license: "GPL-2.0", licenseDeclared: true, version: "3.6.5", minSdk: 21, publishedAt: "2026-02-28T00:00:00Z", size: 48000000, downloadUrl: "https://github.com/videolan/vlc-android/releases/download/3.6.5/VLC-Android-3.6.5-arm64-v8a.apk", releasePage: "https://github.com/videolan/vlc-android/releases/tag/3.6.5", stars: 2600, score: 40.2, recommendedAsset: { arch: "arm64-v8a", abi: "arm64-v8a" }, screenshots: [] },
      { slug: "syncthing-android", name: "Syncthing", owner: "syncthing", ownerType: "Organization", repo: "syncthing-android", repoUrl: "https://github.com/syncthing/syncthing-android", description: "Continuous file synchronization between devices. Decentralised, peer-to-peer, no cloud.", color: "#0891b2", category: "Tools", topics: ["android", "sync", "file-sharing"], language: "Go", license: "MPL-2.0", licenseDeclared: true, version: "1.27.12", minSdk: 21, publishedAt: "2025-10-30T00:00:00Z", size: 28000000, downloadUrl: "https://github.com/syncthing/syncthing-android/releases/download/1.27.12/syncthing-android-1.27.12-Universal.apk", releasePage: "https://github.com/syncthing/syncthing-android/releases/tag/1.27.12", stars: 6400, score: 42.6, recommendedAsset: { arch: "universal", abi: "universal" }, screenshots: [] },
    ],
  };
})();
